version: '3.8'
services:
  postgres-database:
    image: "postgres"
    ports:
    - 5433:5432
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
  pgadmin-client:
    image: "dpage/pgadmin4"
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: "krancki@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
